
@startuml
skinparam style strictuml
skinparam defaultfontname Verdana
title RDCU pour redemarrerJeu
participant ":JeuDeDes" as c
->c : redemarrerJeu()
note right : selon Contrôleur\n(JeuDeDés est \nl'objet racine)
participant "joueurs:\n Map<String, Joueur>" as jm
c -> jm : clear()
note right: selon Expert
@enduml